### ISSUE TITLE
WTF, how did Library got added?

### ISSUE THREAD

**Issue by aytona** [aytona/YogurtEndlessRunner#107]
Was going on autopilot mode and didn't notice that the Library folder somehow bypassed the gitignore and got added to the project. It's not that big of a deal since resolving conflicts is fairly easy, but should take a look at to remove it from the repo.

**Comment by CarloAlbino** [comment]
My branch had the library file for a while, but I would just manually remove them.  When I had the time I removed them and I changed the gitignore file.  That probably messed it up.  Maybe you have your project in a different place.  I don't know.

**Comment by aytona** [comment]
Well in the gitignore, it says to ignore the /[Ll]ibrary/ folder as a whole. What's even more weird is that if you look inside the library folder in GitHub, it only has 1 file inside it. So it partially did ignore like 99% of its content except for that 1 file.

**Comment by aytona** [comment]
Removed the lib folder in github now
