### ISSUE TITLE
GameContoller disappears

### ISSUE THREAD

**Issue by CarloAlbino** [aytona/YogurtEndlessRunner#108]
Sometimes when the game is started after losing the game the game controller reference in game settings disappears.  When Add level is being called I get a NullReferenceException.  

I haven't looked into it yet.

**Comment by aytona** [comment]
What scene would this happen on? I haven't encountered this bug before, and I have restarted the game several times.

**Comment by CarloAlbino** [comment]
In the main scene.  I haven't noticed a pattern yet.

**Comment by aytona** [comment]
This should be fixed by now, re-open if it comes up again.
