### ISSUE TITLE
Add flag sprites to the distance markers

### ISSUE THREAD

**Issue by CarloAlbino** [aytona/YogurtEndlessRunner#123]
## Add flag sprites to the distance markers

![flags_position](https://cloud.githubusercontent.com/assets/7524213/15906406/ac9c6844-2d86-11e6-9bef-687499c3061a.png)

We need to add the sprites to the distance marker like the screenshot shows.  We also need to track the record distance traveled. 

The sprites have already been added to the project.

**Comment by aytona** [comment]
Just added the new distance marker.
Some notes to make: The tilt on the platform seems to be about 54 degrees on the X axis in case this number is needed in the future, also the flag needed to be spawned slightly "higher" (more towards the camera) than the other spawners because obstacles will overlap it.

**Comment by aytona** [comment]
As per the best run flag, is the value in the flag constantly changing? As in, lets say you beat the best run, is it continuously updating that value until its game over? Or only update it once the game is over?

**Comment by CarloAlbino** [comment]
The best run only gets updated when the game is over.  So there would be a flag where your previous best run was, you can then pass it, but you won't see it again that entire run.  Also if there isn't a best run recorded yet I wouldn't show the flag at all.

**Comment by aytona** [comment]
Hm, so it spawns like the other flags but at the position of the player's best record? The image was kind of confusing. The blue flag says 2045m and the purple flag also says 2045m but in a different positions, so I thought the purple flag was just a UI element that stays on the screen all game.

**Comment by CarloAlbino** [comment]
I hadn't noticed that.  I think it would be weird if it was just stationary while everything else was moving.  

I think it just spawns at the best record.  That's how I've seen it in other games.

**Comment by aytona** [comment]
Both flags should be implemented now, just keeping this issue open for any feedback.
The best distance flag shows your best distance to the nearest 2 decimal points, and also doesn't show  unless your best distance is at least greater than 0 (so the player has played at least 1 run)

**Comment by CarloAlbino** [comment]
It looks good. 

This is a something completely different, but I think game needs to be slowed down, I've been playing other endless runners and ours is super fast.  I mention this because the flags aren't really readable, not because of the assets or whatever you did, but because the speed is just too great.  I'll mention it to Kalen at some point, this is really a design issue.

**Comment by aytona** [comment]
Okay, then I guess this issue is done for now. Speed balancing is something else that could be done in the future
