### ISSUE TITLE
GameController.cs deprecated?

### ISSUE THREAD

**Issue by aytona** [aytona/YogurtEndlessRunner#127]
Was working on the best distance stuff and noticed that there is a Game script that is pretty much the GameController script but without all the comments. Are we not using GameController anymore?

**Comment by CarloAlbino** [comment]
Sorry I should have let you know about this.  Yeah, Game has everything needed from GameController.  I just kept FameController because I still wanted the old scene to work.

**Comment by aytona** [comment]
Oh okay, I've only added the saving portion of the best distance flag on game.cs for now.
