### ISSUE TITLE
Merge the menus and game scenes [Discussion]

### ISSUE THREAD

**Issue by CarloAlbino** [aytona/YogurtEndlessRunner#131]
## Merge the menus and game scenes [Discussion]

I though the game would work better with the 2 scenes at first, but the game takes a while to load the Game scene.  I tried to have it load in the background, but the game hung a bit when loading the next scene in the background.  So I think the best thing would be to have everything in the same scene.  We don't need to do this right away, but when we do we will need to make sure of a few things.

- All variables (speed, score, distance) will need to reset because I don't think reloading the scene will be fast enough for the play/replay pace of the game
- Canvases of the menus need to be organized and connected properly

Chris, do you think this is a good idea?  Would you have any alternatives?

**Comment by aytona** [comment]
Having just 1 scene is fine, but I don't know about not be able to reset the scene.
A lot of objects and calculations are initialized using a float and is being calculated to the nearest hundredth. Resetting the scene is a good way to keep these values as close to what is intended without it drifting too far off. 
We could minimize resetting the scene to a minimum, like when changing characters or something.

**Comment by CarloAlbino** [comment]
Yeah, you're right. I hadn't thought of that.  The reason I was there will be a yogurty's ad (that shouldn't be repeated) before the play button, which I guess could be a in a different scene that runs before the main game scene with all the menus and stuff.

**Comment by CarloAlbino** [comment]
I just built the game on my phone and the load times between scenes is not as bad as in editor so it might be fine to keep the scenes split.

**Comment by aytona** [comment]
We could add a loading screen inbetween transitions to make it look a bit better

**Comment by aytona** [comment]
I don't think this issue is needed anymore
