### ISSUE TITLE
Opening Menu character

### ISSUE THREAD

**Issue by aytona** [aytona/YogurtEndlessRunner#134]
Is the waving yogurt suppose to be visible throughout the whole scene? He blocks the text in the stat screen, and is kind of out of place in the character selection screen. I assume this is just temporary but do we know when he's suppose to only appear? We could also just having him move to certain areas of the screen depending on what screen is displayed.

**Comment by CarloAlbino** [comment]
No, it should only be visible on the character select screen.  Sorry I should have fixed that before merging.
