### ISSUE TITLE
No Candy Sopawning

### ISSUE THREAD

**Issue by CarloAlbino** [aytona/YogurtEndlessRunner#136]
I built the game onto my phone, the newest Release with the recent changes you've made (speed item) and I noticed that the candy doesn't spawn anymore.

Did you change something that could have done that?

**Comment by aytona** [comment]
It shouldn't have changed. The only thing I changed in the spawning is how airspawns are. When I tested it, everything is showing as intended.

**Comment by CarloAlbino** [comment]
I just tried it in editor and it's fine, but for some reason on my phone candies don't spawn.  No matter how many time I restart the app.  Weird.

**Comment by CarloAlbino** [comment]
This was just a bad build as far as I can tell
