### ISSUE TITLE
Background Changing

### ISSUE THREAD

**Issue by CarloAlbino** [aytona/YogurtEndlessRunner#137]
## Background Changing

From task list:
> Backgrounds change after a set amount of distance (set in editor), through a list of possible backgrounds/floors

What I think they mean by this is that there will be different 'environments' that change after the distance set int he editor.  Each 'environment' would have a certain amount of tiles that would repeat until it's time to change.  This would be similar to jetpack joyride.

**Comment by aytona** [comment]
I can see this being problematic, either each 'new' background is similar to the others or we need some kind of transition tiles inbetween so it doesn't look weird when the background suddenly changes

**Comment by aytona** [comment]
## Background instructions
![background_instructions](https://cloud.githubusercontent.com/assets/9949395/16866306/0c3d8890-4a39-11e6-8f24-0b40e0f5de2a.jpg)

**Comment by CarloAlbino** [comment]
More instructions:

>
For the backgrounds: have it switch to the new background after X meters (let's say 200 right now)

**Comment by aytona** [comment]
This is going to take longer than expected. As of now the script is about 70% done. But then I would also need to setup the new bg prefabs.

**Comment by CarloAlbino** [comment]
I can work on the prefabs. I'll have time on Monday.

**Comment by aytona** [comment]
The background manager script is done, just need to setup it up on the main Game scene. Also still need to setup the changing BG prefab. Pretty much how the script works is that the continuous(non-changing) BG is the parent and moves as it moved before (named ParentBG). The changing BG (named ChildBG), is a child of the ParentBG and gets switched once the certain distance is met. The new ChildBG is grabbed from a Queue and attached to the ParentBG and dequeued. While the previous ChildBG is detached from the ParentBg and queued back to the waitilist. 

When I did test it on a separate scene there was a bug pertaining a different script. I'm not sure if this will occur in the main Game scene where everything is setup. The only thing I had on the separate scene was the background manager and game manager, so a lot was missing in the scene.

**Comment by aytona** [comment]
This is completed
