### ISSUE TITLE
High Obstacles

### ISSUE THREAD

**Issue by CarloAlbino** [aytona/YogurtEndlessRunner#139]
## High Obstacles

From the task list:
> **Chocolate/High Obstacles**
> -Add a delay before these start spawning (changeable in editor)
> -Allow us to set the frequency of how often these show up, and how quickly that frequency increases
> 
> **High Obstacle Warning**
> -When a chocolate/high obstacle is coming, have a warning sign that shows which lanes will have the obstacle (so the player has a better chance of avoiding it)
> -The warning sign will be an animated sprite

The obstacle spawning script will probably have to be modified to be able to start spawning something new after a certain time.

Also:
> **Bugs**
> -You can sometimes jump over the chocolate (hard to reproduce — if you can't reproduce it, it's not a big deal)

**Comment by aytona** [comment]
The spawning system isn't really built to have delays, because everything is initialized at the start and then updated through coroutines. So this is a bit of a hack, but it works. It'll spawn the large obstacles after x amount of shuffles the ground spawns take. Which is ~3 levels per shuffle

**Comment by CarloAlbino** [comment]
Cool, I'll take care of the 'bug' where you can jump over the chocolate.  I'll just make it longer so that the character can't jump over.

**Comment by CarloAlbino** [comment]
Made the obstacles longer so that it is less likely for the character to jump over them.  Should be good now.

**Comment by CarloAlbino** [comment]
I forget about the High Obstacle warning.

**Comment by aytona** [comment]
I've added a script that does a blink effect similar to the player effect. Just need to add the warning sprite gameobject in the scene. I don't think we have the sprite for it though.

**Comment by aytona** [comment]
Well since there is no warning sign sprite, I just added a text mesh instead. I think everything in this issue is done but I do feel like the large obstacles are a bit too long. I might have accidentally changed it but I'm not sure what the scale of it was before.

**Comment by aytona** [comment]
I replaced the text mesh into the sprite. This should be done by now
