### ISSUE TITLE
Jumping/Landing Effects

### ISSUE THREAD

**Issue by CarloAlbino** [aytona/YogurtEndlessRunner#140]
## Jumping/Landing Effects

From the task list:
> -Spawn/play a sprite animation at the character's feet when they jump and when they land (allow these to be separate sprites)
> -Just use a placeholder for now

These can use the same system I have for the 'collect' and 'hit' animations.

**Comment by aytona** [comment]
Tried importing it but the files turn blank when I checked it out in the editor

**Comment by CarloAlbino** [comment]
Done
