### ISSUE TITLE
Add new collectable items

### ISSUE THREAD

**Issue by CarloAlbino** [aytona/YogurtEndlessRunner#146]
## Add new collectable items

We need to add the new collectable meshes to replace the old candies.  

Kalen:
> 
For the toppings: the toppings should pick a random model when spawned, but we need to keep track of what they are when the player picks them up (for challenges a little later down the line -- like collect 10 blueberries, etc.)

For this milestone, we just need to have the collectable item randomly pick a skin when spawned.

**Comment by aytona** [comment]
So the function of random mesh for toppings/candy has been added but it doesn't look that pretty. Probably need to fiddle with the material or texture settings to make it look more like part of the game.
