### ISSUE TITLE
Upgrading to Unity 5.4

### ISSUE THREAD

**Issue by aytona** [aytona/YogurtEndlessRunner#150]
We should upgrade to 5.4 for the next milestone. It includes a lot of improvements like Physics drift (which the player kind of does).

More info here: https://unity3d.com/unity/whats-new/unity-5.4.0

**Comment by CarloAlbino** [comment]
I'm not completely opposed to it.  I realized that I'm doing something wrong with the physics.  The jump uses physics, but the patent object of the player can be moved without physics.  There isn't a way that both jump and move can be done at once, but maybe frame perfect inputs might mess up the physics and make the player fly off screen.  Or I could be the collision, doesn't calculate properly when the speed of the jump gets to a certain point.
