### ISSUE TITLE
Settings Screen

### ISSUE THREAD

**Issue by CarloAlbino** [aytona/YogurtEndlessRunner#79]
## Setting Screen

New menu for setting:
- Disable sounds (Volume Control?)
- Disable Ads

**Comment by CarloAlbino** [comment]
UI part is added, but no functionality.

**Comment by aytona** [comment]
Added toggle-ability for both the sounds and ads button. I removed sounds pausing when the game is paused, instead I put it on toggle of that sound button. Ads toggle does nothing for now since we don't have an ad functionality yet. It should be a quick edit when that thing is fixed up
