### ISSUE TITLE
Create a new obstacle type

### ISSUE THREAD

**Issue by CarloAlbino** [aytona/YogurtEndlessRunner#96]
## Create a new obstacle type

From Kalen's message:
> -Create a new obstacle type (just use primitives for art -- assets aren't finished yet) that is too large to jump over (so you have to switch lanes if it's in front of you), and add it to the obstacle spawner (spawns maybe 10% of the time, compared to the normal obstacles)

**Comment by CarloAlbino** [comment]
Except for the 10% of the time, this is done.  The system is not currently set up for percentages of obstacles.

**Comment by aytona** [comment]
Reopened issue, I don't think we want the new obstacle to spawn on all 3 lanes. It makes you insta lose the game especially when these obstacles spawn at the start

**Comment by CarloAlbino** [comment]
Up thought I had fixed this.  This has something to do with your script that decides how many to spawn.  I don't know why but sometimes it spawns 3 even when I set it up to only spawn 1 or 2.

**Comment by CarloAlbino** [comment]
I think I fixed it again.  I changed Start to Awake, it works in my tests so far.
