### ISSUE TITLE
Distance Flags

### ISSUE THREAD

**Issue by CarloAlbino** [aytona/YogurtEndlessRunner#99]
## Distance Flags

From Kalen's message:
> -Distance flags --> a background element that spawns, and has the text for how far the player has currently traveled (so when the player passes the 10m flag, they've run 10m). Set it to display every 25m for now. Placeholder art for now (can just use a text mesh or whatever is easiest), as it's currently being worked on. Text will have to display dynamically, so we don't have to make a separate asset for every distance marker.

**Comment by aytona** [comment]
Not sure if I'm overthinking this. But its going to actually take longer than expected. Trying to find a formula on how to get the offset, so I can spawn the flag having a certain number on it before that distance is reached until it passes the player.

**Comment by CarloAlbino** [comment]
Sorry for being late with an answer, but I've been thinking of how to do this.

The distance between the flag spawn and the player should always be the same no matter how fast the game is moving.  If you can get that distance then you can spawn the flag when the player's distance is at a milestone minus the distance of the player to flag spawn location.

I understand that finding the distance is what you are having difficulty with, but I think it's a constant and you don't need a formula.  I'm going to try to find that constant.

**Comment by CarloAlbino** [comment]
The distance between the player and the obstacle.pickup spawn point:
- On iPad is 4.125m
- On iPhone4 is 4.305m
- On iPhone5 is 4.535m

This is a constant at any speed plus or minus 0.05m, which should be fine for our purpose.

So you can probably use these measurements to spawn the 25m flag when the player is at 20.875m when on an iPad, for example.

**Comment by aytona** [comment]
That's what I thought at first but the speed is not constant, its gradually increasing. So the initial speed of the flag is not the same as the final speed of the flag unless it has already hit the speed cap initially.

I wrote the average speed formula on the MarkerSpawner script but changed it since I need to find the time (Since everything in game is determined by time at the moment, not actually by speed/velocity or acceleration). 

// Average Speed: s = d/t
	// Known: Speed of flag, and distance it needs to travel (s and d)
	// Find: Total time (t)
	// Time formula: t = d/s
	// Total distance = markerspaner.x - player.x
	// Speed = gamesettings.gamespeed (need average speed)

So the offset would be, instead of me spawning as soon as the distance hits 25m, it would spawn to on offset of time, so when it actually reaches 25m, it'll be at 0t

At the same time, I do somewhat feel like I'm over complicating this a bit.

**Comment by CarloAlbino** [comment]
Those measurement that I made were made with a marker moving at the speed of the platforms, the game speed.  I tried at multiple speeds wether it is slow or at max speed the distance covered is the same, even when the speed is variable.

**Comment by CarloAlbino** [comment]
Maybe you can offset with distance instead of time.  If the player is at 25minus offset then spawn the flag

**Comment by aytona** [comment]
I'll test it. The problem I see is that it's assuming the speed will be constant. But if, like you said, the speed doesn't matter, then it should be fine.

**Comment by aytona** [comment]
As of right now, the minimum distance the flag needs is ~30m. The only bug right now is the flag spawning multiple times. Update is too fast

**Comment by aytona** [comment]
This is technically done for now, but the minimum flag distance is 30m.

**Comment by CarloAlbino** [comment]
Fixed the distance thing, now it can be 25m.
